# Generated by Django 3.2.9 on 2021-12-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('nickname', models.TextField()),
                ('name', models.TextField()),
                ('profile_image', models.TextField()),
            ],
        ),
    ]
