# Generated by Django 3.2.10 on 2022-01-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learningspoons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('nickname', models.TextField()),
                ('name', models.TextField()),
                ('profile_image', models.TextField()),
            ],
        ),
    ]
