# Generated by Django 3.2.10 on 2022-01-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220119_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='primary_address',
            field=models.BooleanField(default=False),
        ),
    ]
