# Generated by Django 3.2.10 on 2022-01-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('product_id', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'unique_together': {('email', 'product_id')},
            },
        ),
    ]
