# Generated by Django 3.2.10 on 2022-01-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
