# Generated by Django 3.2.10 on 2022-02-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_productreview_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('product_id', models.IntegerField()),
                ('address', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
