# Generated by Django 3.2.10 on 2022-01-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_productreview_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('email', models.TextField()),
            ],
        ),
    ]
