# Generated by Django 3.2.10 on 2022-02-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_productreview_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
