# Generated by Django 3.2.10 on 2022-02-06 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.product'),
        ),
    ]
