# Generated by Django 3.2.10 on 2022-02-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_alter_history_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='product_id',
            new_name='product',
        ),
    ]
