# Generated by Django 3.2.10 on 2022-02-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_product_name'),
        ('content', '0012_alter_favoriteproducts_unique_together'),
    ]

    operations = [
    ]
