# Generated by Django 3.2.10 on 2022-02-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_merge_20220206_0258'),
        ('content', '0013_rename_product_id_history_product'),
    ]

    operations = [
    ]
